### PR TITLE
Create Doctor and AddDoctorDetails

### PR DESCRIPTION
**Pull request by ShatabdiBhise**

### CODE REVIEW

**Comment by adiaholic** [comment]
@ShatabdiBhise when creating a branch, try keeping the branch name as relevant as possible. It reduces the pain of checking commits on that branch before merging it.
For eg: A branch named `doctorFeatures` can include all commits related to doctor's functionalities. Similarly there can be a different branch for `patientFeatures`.
It looks quite unnecessary in the beginning but will prevent a lot of confusion in later stages.

**Comment by ShatabdiBhise** [comment]
Okayy will sure do it from next time!

**Comment by ShatabdiBhise** [comment]
I think we should keep height and weight for the patient because it's
necessary sometimes when you go to a doctor. And even age, because it helps
them give prescriptions accordingly.

**Comment by adiaholic** [comment]
> I think we should keep height and weight for the patient because it's necessary sometimes when you go to a doctor. And even age, because it helps them give prescriptions accordingly.

Merging this branch. If more changes are expected, feel free to push another PR.

**Comment by DeadKernel** [comment]
@ShatabdiBhise I meant in create, creation does not have age gender and all that. It should be there in addDetails not creation

**Pull request merged**
